### ISSUE TITLE
worked example

### ISSUE THREAD

**Issue by ioannsys** [paleg/libadclient#1]
Hello! Please, write true example with this lib.
ty, regards.

**Comment by paleg** [comment]
Both examples (c++ and python) from README.md are true, just replace parameters with your values (AD domain controllers, bind username and password, search base, users and groups).
What problems do you have to got it to work?

**Comment by ioannsys** [comment]
I use Debian Jessie. I install libldap from repository (apt-get install libldap-2.4-2 libldap2-dev) and libsasl2. After command "scons install", created .so file, copied to /usr/share/lib. But this do not work. I manually copy this file to /usr/lib. Now program work, but always return error: invalid creds.
See:
[code="C++"]
#include <iostream>
#include <adclient.h>

using namespace std;
int main()
{
    adclient ad;

```
try
{
    ad.login("ldap://192.168.1.1", "ioann.sys@lab.local", "labLDAP123!", "dc=lab,dc=local");
}

catch(ADBindException &ex)
{
    cout << "ERROR_STRING: " << ex.msg << endl << "ERROR_CODE = " << ex.code << endl;
    return 1;
}


cout << "Hello World!" << endl;
return 0;
```

}
[/code]

But ldapsearch (from package ldap-utils) with parameters: -H "ldap://192.168.1.1" -D "ioann.sys@lab.local" -w "labLDAP123!" -b "dc=lab,dc=local"
work and return for me all records.

**Comment by paleg** [comment]
ldapsearch in your example uses simple authentication, libadclient uses SASL bind with digest-md5 as AD refuses to do some actions (e.g. change passwords) if bind was with clear text authentication.

So you should try:
1. remove domain part from username (i guess that is the real problem):
`ad.login("ldap://192.168.1.1", "ioann.sys", "labLDAP123!", "dc=lab,dc=local");`

2a. check reverse dns records for 192.168.1.1:

<pre>
$ dig @your_ns_here -x 192.168.1.1 +short +answer
dcname.lab.local.
</pre>

2b. check spn record for this DC from `cmd`

<pre>
setspn -L dcname.lab.local
</pre>

it must contain `ldap/dcname.lab.local`
If there is no reverse dns record for DC (then you have problems with your AD setup), spn list must contain `ldap/192.168.1.1`

P.S. Probably i should provide both auth methods (simple and SASL) in library.

**Comment by ioannsys** [comment]
Paleg, after your commit (#60), i try whithout domainpart in username. So, your first variant - true for me. Big thank you!
