### ISSUE TITLE
Better error reporting if we are not connected to the AD ?

### ISSUE THREAD

**Issue by sysblade** [paleg/libadclient#11]
Currently, when calling a method like GetUserDisplayName or any other before connecting to the AD, we are getting errors like this (For Go here):

```
interface conversion: interface {} is runtime.errorString, not string
```

I've spend sometime to find that I just forgot to connect before.

Would it be interesting to have some kind of check to get more explicit errors ?

**Comment by paleg** [comment]
Just did a quick test, it returns error correctly. What is your code?
```
package main

import (
    "fmt"
    "github.com/paleg/libadclient"
)

func main() {
    adclient.New()
    defer adclient.Delete()

    if _, err := adclient.GetUserDisplayName("blah"); err != nil {
        fmt.Printf("Failed to get user display name: %v\n", err)
    }

}
```

Output:
`Failed to get user display name: 2: Failed to use LDAP connection handler`

**Comment by sysblade** [comment]
Hello, I continued the development and now I can't reproduce it anymore, maybe I had something wrong.

I think we can close this issue for now :)

Thank you
