### ISSUE TITLE
[golang] Getting binary data

### ISSUE THREAD

**Issue by fabiang** [paleg/libadclient#12]
Hello,

I want to receive the SID from an user in Active Directory which is a binary value and print it as string later. I see `getBinaryObjectAttribute` isn't implemented yet, so I'm using `GetObjectAttribute` instead. How can I convert the string to the expected byte slice?

**Comment by paleg** [comment]
Actually I have never used `getBinaryObjectAttribute` (failed to find use-case), it is untested and should not work, so I just removed it :).

Regarding getting binary data - I made some changes, so `getObjectAttribute` should now return binary data the same way as string data, but only for c++ and golang (in python it will return binary data up to NULL character). I also added decodeSID function to convert binary SID to string representation.

You can use it in the following way:
```golang
if sid, err := adclient.GetObjectAttribute(user, "objectSid"); err == nil {
    fmt.Printf("objectSid encoded is %q\n", sid[0])
    fmt.Printf("objectSid decoded is %v\n", adclient.DecodeSID(sid[0]))
}
```

I tested it slightly and it works for me, but YMMV. Please test and let me know if it works for you.

**Comment by fabiang** [comment]
Thank you very much. It's working like a charm. Closing this :)

**Comment by bwmarrin** [comment]
This came up on Google when searching for a solution to this problem.  So, in case anyone else ends up here.  I ran into this issue and wrote a small utility package that can decode the objectSID.

https://github.com/bwmarrin/go-objectsid
