### ISSUE TITLE
Moving objects

### ISSUE THREAD

**Issue by fabiang** [paleg/libadclient#13]
Hello,

is it possible to move objects with this library? Background: I need to move users whenever the company they belonging to changes.

**Comment by paleg** [comment]
No, at the moment there is no such method available. But it should not be too hard to implement this. I will let you know when it will be ready (eta - next week).

**Comment by paleg** [comment]
It is ready - MoveUser(user, new_container). User could be short name or distinguished name, and new_container should be distinguished name of OU to move user to.
Please test if it works for you.

**Comment by fabiang** [comment]
I've tested it and it's working for me. Thanks :+1:
