### ISSUE TITLE
[golang] How to set attribute "userAccountControl"?

### ISSUE THREAD

**Issue by fabiang** [paleg/libadclient#14]
Hello,

I'm trying to set the attribute "userAccountControl" to a freshly created user, but I get "ldap_modify_ext_s: Invalid syntax"

This is what I'm doing:

```go
userAccountControl, _ := adclient.GetObjectAttribute(username, "userAccountControl")
userAccountControlInt, _ := strconv.ParseInt(userAccountControl[0], 10, 32)

fmt.Printf("%d\n", userAccountControlInt) // e.g. 66048

// remove flag 
userAccountControlNew := (userAccountControlInt ^ 65536)

fmt.Printf("%d\n", userAccountControlNew) // 512 = normal account

err = adclient.SetObjectAttribute(username, "userAccountControl", string(0))
```

Can you help?
Thanks

**Comment by paleg** [comment]
If I remember correctly Active Directory could refuse userAccountControl manipulations without setting password first to freshly created users. Have you set password before userAccountControl change?

**Comment by fabiang** [comment]
Yes. I did and I can login with the password I've created for the user.

**Comment by paleg** [comment]
ok, i will check this

**Comment by paleg** [comment]
It works as expected for me.

I noticed that you are using `string(0)` - it is wrong due two reasons:
1. there should be `userAccountControlNew`, to `0`
2. you can't use `string()` for such conversion as it will return character with code equals to `userAccountControlNew`. You should use `strconv.FormatInt(userAccountControlNew, 10)` instead.

**Comment by fabiang** [comment]
Thanks of cause I've to convert it with FormatInt(). `string(0)` was just a test that I didn't changed back. Thank you it's working now.
