### ISSUE TITLE
How to check if the user password is expired ?

### ISSUE THREAD

**Issue by sysblade** [paleg/libadclient#16]
Hello,

Simple question, is there a way to check if the user password is expired ?
I'm doing a lot of check for the login (To help the user troubleshoot why it cannot login on other systems of the active directory) and the only thing I miss is checking if the password has expired, I could not find any bundled method to do this, is there any AD parameter I can check to do so ?

Could it be interesting to add a IfUserPasswordExpired(user) ?

Thanks

**Comment by ioannsys** [comment]
Hello!
You can get user attributes like as: "accountExpires", "pwdLastSet" + yr expired period. for more opportunities y need use "userAccountControl" (see https://support.microsoft.com/en-us/help/305144/how-to-use-the-useraccountcontrol-flags-to-manipulate-user-account-pro)

**Comment by paleg** [comment]
I don't think that it is possible to detect password expiration directly as there is no such attribute for user object. You can try to do calculation based on hardcoded password expiration policy.

```golang
// pw expiration time - 90 days
pwMaxAge := 60 * 60 * 24 * 90
controls, _ := adclient.GetUserControls(username)
if controls["dontExpirePassword"] {
    fmt.Println("don't expire password")
    return
}
if controls["mustChangePassword"] {
    fmt.Println("must change password (admin request)")
    return
}
pw, _ := adclient.GetObjectAttribute(username, "pwdLastSet")
pwNum, _ := strconv.ParseInt(pw[0], 10, 64)
pwPosix := adclient.FileTimeToPOSIX(pwNum)
tm := time.Unix(pwPosix, 0)
timeDiff := int(time.Now().Sub(tm).Seconds())
if timeDiff >= pwMaxAge {
    fmt.Printf("pw for '%v' expired, last set '%v'\n", username, tm)
    return
}
fmt.Println("passed all checks")
```

I just added `FileTimeToPOSIX` to python and golang, so pull new code to use it.

Above written code can have an issue with UTC/Local time convertion, I'm not sure how AD stores pwdLastSet.

**Comment by sysblade** [comment]
Thanks I will try that :)

I've recently changed the max password age on my policies, do you know if this would affect all the passwords already set (In this case your solution would work) or it's like something put by object and then it would only affect new passwords (Where in this case your solution will only work for the passwords following the new expiration policy)

**Comment by paleg** [comment]
In `pwdLastSet` AD stores timestamp when password was changed last time, it is not relative to passwords policy time, it is a definite timestamp. So changing max password age should not affect above mentioned algorithm.

**Comment by sysblade** [comment]
Great :)
Thanks for all your answer.

Maybe it could be interesting to add it as something like IfPasswordOlderThan(user string, days int) or something like that ?

**Comment by paleg** [comment]
I don't think that such boundary case should be added to library. I'd prefer to keep it as is (pwLastSet attribute + method to convert timestamp).
