### ISSUE TITLE
undefined symbol: _ZN8adclient5loginESsSsSsSsb

### ISSUE THREAD

**Issue by ioannsys** [paleg/libadclient#2]
## include <iostream>

using namespace std;
int main()
{
    string host = "ldap://192.168.1.1";
    string userdn = username->text().toUTF8();
    string userpw = userpass->text().toUTF8();
    cout << userdn << endl;
    cout << userpw << endl;
    string userbs = "DC=lab,DC=local";
    string tmp = "Connecting to русские буквы " + host;
    this->printn(tmp);

```
tmp = "Current data:\tLogin = " + userdn + "\n\r\t  Password =  " + userpw + "\n\r\t  Search Base = " + userbs;
this->printn(tmp);

try
{
    ad.login(host, userdn, userpw, userbs);
}

catch(ADBindException &ex)
{
    tmp = "ERROR: " + ex.msg;
    printn(tmp);
}
```

}

this code comiled, but on runtime, i get error undefined symbol: _ZN8adclient5loginESsSsSsSsb

**Comment by ioannsys** [comment]
emm.. My ${PATH} environment can not provide /usr/local/lib directory.
Please, fix SCONS constructor to copy *.so files more std paths, that /usr/local/lib

Thank you

**Comment by paleg** [comment]
I guess you pulled recent changes and recompiled, so now you have two copies of library (installed in different places). One is used while compiling, another when running. Remove all copies and then do:

<pre>
$ cd /usr/local/src/libadclient   // where you pulled sources
$ scons -c
// this will install header into /usr/local/include, and lib into /usr/local/lib
$ scons install    
$ g++ -I/usr/local/include -L/usr/local/lib -ladclient test.cpp
$ ./a.out
</pre>

Of course /usr/local/lib should be added to ld search path.

btw with recent changes you can:
1) use domain name as a first parameter for login(), ldap servers will be resolved from DNS srv records.
2) switch between simple and SASL auth with last boolean parameter for login(). true (default) - SASL, false - simple.
e.g.:

<pre>
string domain = "lab.local";
....
// default
ad.login(domain, userdn, userpw, userbs, true);
// or
ad.login(domain, userdn, userpw, userbs, false);
</pre>

**Comment by paleg** [comment]
you can use `scons install prefix=/usr` to install into /usr/include and /usr/lib, but you should not :), all files not from package manager should be in /usr/local.
better add /usr/local/lib into ld search path

**Comment by ioannsys** [comment]
Yes, you right! Very big thank for you!
