### ISSUE TITLE
What would it take to make this work in NodeJS?

### ISSUE THREAD

**Issue by kheide** [paleg/libadclient#21]

**Comment by paleg-dj** [comment]
I believe that it is possible with [swig](www.swig.org) in the same way as I already did for golang.
I tried following steps as per documentation:
```
$ swig -c++ -javascript -node adclient.swigcxx
$ cat > binding.gyp << EOF
{
  "targets": [
    {
      "target_name": "adclient",
      "sources": [ "adclient_wrap.cxx" ]
    }
  ]
}
EOF
$ node-gyp build
```
but build failed with some nodejs specific errors and it looks like they are related to incompatible combination of swig and nodejs version (3.0.12 and v8.12.0). Unfortunately I know nothing about nodejs to fix all these errors.

**Comment by kheide** [comment]
I’ll take a look and report back!
