### ISSUE TITLE
Not working in Ubuntu 18.04

### ISSUE THREAD

**Issue by ricardobiundo** [paleg/libadclient#22]
I tried my best but I still get this error:
/usr/bin/ld: warning: libkrb5.so.26, needed by //usr/lib/x86_64-linux-gnu/libgssapi.so.3, may conflict with libkrb5.so.3
After some research I found that is a problem of libldap2-dev version of krb5 conflicting with libkrb5 (https://bugs.launchpad.net/ubuntu/+source/openldap/+bug/1772530)
I tried using old dap version:
sudo apt install liblapack-dev libopenblas-dev
but still nothing.
Anyone can help me?

**Comment by paleg** [comment]
1. Just tried on a freshly installed Ubuntu 18.04, works as expected:
```bash
git clone https://github.com/paleg/libadclient.git
cd libadclient
apt-get install scons g++ libldap2-dev libkrb5-dev libsasl2-dev libsasl2-modules-gssapi-mit
scons install
ldconfig
g++ test/test.cpp -o adclient -ladclient
```
2. You can build and use it in a Docker container, look at [Dockerfile@test](https://github.com/paleg/libadclient/blob/test/Dockerfile) as an example

**Comment by ricardobiundo** [comment]
I think I might have been missing a library or something.
I thank you deeply. I can finally continue with my project. I suggest adding the instructions to the read-me.

**Comment by ricardobiundo** [comment]
Uh. I forgot so say that I'm trying to install the Go Package and its still giving me the same error. I though that it was gone but I noticed it while trying to run the example.

**Comment by ricardobiundo** [comment]
> Uh. I forgot so say that I'm trying to install the Go Package and its still giving me the same error. I though that it was gone but I noticed it while trying to run the example.

# github.com/paleg/libadclient
/usr/bin/ld: warning: libkrb5.so.26, needed by //usr/lib/x86_64-linux-gnu/libgssapi.so.3, may conflict with libkrb5.so.3
# github.com/paleg/libadclient
adclient.h:61: Warning 315: Nothing known about 'std::cout'.
adclient.h:62: Warning 315: Nothing known about 'std::endl'.
