### ISSUE TITLE
STARTTLS/TLS/SSL support

### ISSUE THREAD

**Issue by fabiang** [paleg/libadclient#24]
Hi,

currently I want to make the switch my connections to TLS/SSL. I've tried to specify the URI in the form `ldaps://<domaincontroller>.<domain>:636` and I get the following error:

```
err: 4: No suitable connection uries found
```

I guess the underling CPP library does support the LDAPS scheme, while I'm pretty sure that OpenLDAP and SunLDAP do.

Apart from that I don't see how to force STARTTLS on a connection and it seems it is not tried at all to establish a secure connection (even when available).

Can we have another option to force STARTTLS and support the LDAPS scheme?

Thank you.

**Comment by paleg** [comment]
Yes, "ldap" scheme is hardcoded, preventing usage of LDAP over SSL. And LDAP over TLS is not implemented. Check [feature-tls](https://github.com/paleg/libadclient/compare/master..feature-tls) branch where I adjusted cpp library to support LDAPS/StartTLS and let me know how it goes.

**Comment by fabiang** [comment]
The feature branch works perfectly with both STARTTLS and LDAPS. I've just added a PR for the Go wrapper to support the TLS options too.

**Comment by fabiang** [comment]
Tested with current master after your merge and everything is working as expected.
 Thanks!
