### ISSUE TITLE
bug in method adclient::getUserGroups(string userdn);

### ISSUE THREAD

**Issue by ioannsys** [paleg/libadclient#3]
This method can not provide primary group "Domain Users", but i can see others group.

**Comment by paleg** [comment]
It is a limitation of AD [1]. The memberof attribute of the user object is not populated with the primary group name.
However, you can find primary user group, but it involves some magic and not very efficient [2]:

<pre>
>>> primary_group = ad.getObjectAttribute("user", "primaryGroupID")[0]
>>> primary_group
'513'
>>> for group in ad.getGroups():
...   if ad.getObjectAttribute(group, 'primaryGroupToken')[0] == primary_group:
...     print(group)
...     break
...
Domain Users
</pre>
1. https://support.microsoft.com/en-us/kb/275523
2. https://support.microsoft.com/en-us/kb/321360

**Comment by ioannsys** [comment]
Need create defines in header file for magic values in attributes. Oleg, thank you for this informaton!

p.s.: it is actualy for Windows Server 2012 R2 too.
