### ISSUE TITLE
Connection Issue

### ISSUE THREAD

**Issue by imRohan** [paleg/libadclient#6]
This isnt an issue per say, Im pretty sure im doing something wrong.

Could you clarify what the "Site" param is used for? I can ping my server however I cannot get a connection through the adclient (go).

My network admin has provided a domain, username/password as well as "dc=domain,dc=com"

**Comment by paleg** [comment]
It is [Active Directory Site](https://technet.microsoft.com/en-us/library/cc754697\(v=ws.11\).aspx).
It can be used to find closest DC to your location. You can leave it blank (omit setting this parameter) - then DCs from root domain will be used.
