### ISSUE TITLE
Getting Error While running sample program for GOLANG. I have installed the openldap as well.

### ISSUE THREAD

**Issue by aniketofficial** [paleg/libadclient#7]
![libclient](https://cloud.githubusercontent.com/assets/8258186/24344944/6cb2c552-12eb-11e7-94e5-ee637b22f185.PNG)

**Comment by paleg** [comment]
It looks like compiler fails to find shared libraries for ldap, sasl, kerberos, etc.
Unfortunately I have no experience with mingw and can't help you with this.
