### ISSUE TITLE
cross compile to windows

### ISSUE THREAD

**Issue by foodforarabbit** [paleg/libadclient#8]
so I'm trying to build my project for windows (from linux mint. building normally to linux target works perfectly) with this command:

```
GOOS=windows GOARCH=386 CGO_ENABLED=1 CXX=i686-w64-mingw32-g++ CC=i686-w64-mingw32-gcc go build
```

and I'm getting this error:

```
In file included from vendor/github.com/paleg/libadclient/adclient.cpp:2:0:
vendor/github.com/paleg/libadclient/adclient.h:9:18: fatal error: ldap.h: No such file or directory
compilation terminated.
```

looking for ldap.h on my system, here is what I have:
```
/usr/i686-w64-mingw32/include/ntldap.h
/usr/i686-w64-mingw32/include/winldap.h
/usr/include/ldap.h
/usr/share/mingw-w64/include/ntldap.h
/usr/share/mingw-w64/include/winldap.h
/usr/x86_64-w64-mingw32/include/ntldap.h
/usr/x86_64-w64-mingw32/include/winldap.h
```

Is this library incompatible with windows or am I doing something wrong?

**Comment by paleg** [comment]
I'm not sure that you will be able to cross compile it for windows as it highly depends of linux-specific things, such as new openldap interface, krb5, resolv.h, etc. Windows uses other syscalls (as well as headers) for all this things.
