### ISSUE TITLE
SWIG Issues

### ISSUE THREAD

**Issue by alexarena** [paleg/libadclient#9]
When we tried to build and run the sample app, we got the following error:
```
adclient.h:61: Warning 315: Nothing known about 'std::cout'.
adclient.h:62: Warning 315: Nothing known about 'std::endl'.
go build github.com/paleg/libadclient: build output "/var/folders/dx/3d4k2yp11d7_twlknf2r0vk80000gn/T/go-build911557826/github.com/paleg/libadclient/_obj/adclient.go" already exists and is not an object file
```
I think this is something to do with SWIG and I'm not sure if it's something that you can help with.

We're running go 1.8.1 on macOS 10.11.6 with SWIG 3.0.12

Thanks!

**Comment by paleg** [comment]
it is caused by go 1.8, not swig. It works as expected with go 1.7.5.
Please, try following sequence and let me know if it works:
```
cd $GOPATH/src/github.com/paleg/libadclient
mv adclient.go adclient_wrapper.go
cd
go build github.com/paleg/libadclient
```

**Comment by sysblade** [comment]
I tried that.

The error doesn't appear anymore (But I didn't try yet to use the library)

Thanks :)
